name: signum_beat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  just_audio:
  audio_service:
  audio_metadata_reader: ^1.0.0
  file_picker:
  cupertino_icons: ^1.0.6
  html_unescape: ^2.0.0
  provider: ^6.1.2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  dart_des: ^1.0.2
  google_fonts: ^6.2.0
  flutter_cache_manager: ^3.3.2
  flutter_sliding_up_panel: ^2.1.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  path_provider:
  id3_codec: ^1.0.3
  video_player: ^2.9.2
  flutter_local_notifications: ^17.2.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true