// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCGwYj4l2Qljp7E2xZKTdN99vt0IMCerEs',
//     appId: '1:455495973108:web:ec973a86fbfd027178c6a1',
//     messagingSenderId: '455495973108',
//     projectId: 'watchit-8c425',
//     authDomain: 'watchit-8c425.firebaseapp.com',
//     storageBucket: 'watchit-8c425.appspot.com',
//     measurementId: 'G-X2T6X2NMB5',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDdjTUXEFIax3feY2rsdijocfKekUFdbpw',
//     appId: '1:455495973108:android:50c8405e89df00a778c6a1',
//     messagingSenderId: '455495973108',
//     projectId: 'watchit-8c425',
//     storageBucket: 'watchit-8c425.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBX-LfXkTLFISfvtI8S37n6fQgMJE56Avk',
//     appId: '1:455495973108:ios:72343700963b542f78c6a1',
//     messagingSenderId: '455495973108',
//     projectId: 'watchit-8c425',
//     storageBucket: 'watchit-8c425.appspot.com',
//     iosBundleId: 'com.example.watchIt',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBX-LfXkTLFISfvtI8S37n6fQgMJE56Avk',
//     appId: '1:455495973108:ios:72343700963b542f78c6a1',
//     messagingSenderId: '455495973108',
//     projectId: 'watchit-8c425',
//     storageBucket: 'watchit-8c425.appspot.com',
//     iosBundleId: 'com.example.watchIt',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCGwYj4l2Qljp7E2xZKTdN99vt0IMCerEs',
//     appId: '1:455495973108:web:47b1f203390df86178c6a1',
//     messagingSenderId: '455495973108',
//     projectId: 'watchit-8c425',
//     authDomain: 'watchit-8c425.firebaseapp.com',
//     storageBucket: 'watchit-8c425.appspot.com',
//     measurementId: 'G-M9JY2W2GWZ',
//   );
// }
